%define rpm_device a5y17lte
%define device a5y17lte
%define multiple_rpms 1

%define dsd_path ./

Requires(post): coreutils
Requires(post): libcap

%include droid-system-device/droid-system.inc

# rest of this file is autogenerated. do not edit
%post
[ -e /system/xbin ] && chown 0:2000 /system/xbin ||:
[ -e /system/xbin/7z ] && chown 0:2000 /system/xbin/7z ||:
[ -e /system/xbin/bash ] && chown 0:2000 /system/xbin/bash ||:
[ -e /system/xbin/htop ] && chown 0:2000 /system/xbin/htop ||:
[ -e /system/xbin/nano ] && chown 0:2000 /system/xbin/nano ||:
[ -e /system/xbin/pigz ] && chown 0:2000 /system/xbin/pigz ||:
[ -e /system/xbin/rsync ] && chown 0:2000 /system/xbin/rsync ||:
[ -e /system/xbin/unrar ] && chown 0:2000 /system/xbin/unrar ||:
[ -e /system/xbin/vim ] && chown 0:2000 /system/xbin/vim ||:
[ -e /system/xbin/wget ] && chown 0:2000 /system/xbin/wget ||:
[ -e /system/xbin/zip ] && chown 0:2000 /system/xbin/zip ||:
